version: "3"

services:
  api:
    container_name: rokket-api
    build: .
    restart: always
    ports:
      - "80:8080"
    links:
      - mongo

  mongo:
    container_name: rokket-db
    image: mongo
    ports:
      - "27017:27017"
