version: "3"

services:
  api:
    container_name: rokket-api
    build: .
    restart: always
    ports:
      - "80:8080"

  mongo:
    container_name: rokket-db
    image: mongo
    expose:
      - "27017"
