version: "3"

services:
  backend:
    container_name: api_rokket-api
    build: .
    restart: always
    ports:
      - "8080:8080"

  mongo:
    container_name: api_rokket-db
    image: mongo
    expose:
      - "27017"
